services:
  db:
    image: postgres:16-alpine
    restart: always # Автостарт!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: venius24/foodgram_backend:latest
    restart: always # Автостарт!
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./static/:/app/static/
      - ./data/media/:/app/media/

  frontend:
    image: venius24/foodgram_frontend:latest
    restart: always

  nginx:
    image: nginx:1.19.3
    restart: always # Автостарт!
    ports:
      - "80:80"
      - "443:443" # Теперь открываем и 443 порт
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/usr/share/nginx/html/
      - ./static/:/var/html/static/
      - ./data/media/:/var/html/media/
      # ПРОКИДЫВАЕМ СЕРТИФИКАТЫ ИЗ СИСТЕМЫ В КОНТЕЙНЕР
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  frontend_static:
