server {
    listen 80;
    server_name venius24.ddns.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Основной блок HTTPS
server {
    listen 443 ssl;
    server_name venius24.ddns.net;

    # Внутренний DNS Docker (чтобы Nginx не падал при старте)
    resolver 127.0.0.11 valid=30s;

    ssl_certificate /etc/letsencrypt/live/venius24.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/venius24.ddns.net/privkey.pem;

    # Документация API
    location /api/docs/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/redoc.html;
    }

    # API и Админка — используем переменные, чтобы Nginx не падал
    location /api/ {
        set $backend_host backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://$backend_host:8000;
    }

    location /admin/ {
        set $backend_host backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://$backend_host:8000;
    }

    location /static/admin/ {
        alias /var/html/static/admin/;
    }

    location /static/rest_framework/ {
        alias /var/html/static/rest_framework/;
    }

    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    location /media/ {
        alias /var/html/media/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri /index.html;
    }
}
